#!/bin/bash
var_RUNTIME_PACKAGES="svn"

phase_preparation ()
{
	# All things that need to be done manually first
	notify "A few manual things need to happen first..."
	if `ask_yesno "Do you want to (re)-configure your networking?"`
	then
		donetwork #configure network by using library
	else
		notify "Ok. skipping network config"
	fi
	SVN_USERNAME=dieter
	ask_password svn
	SVN="svn --username $SVN_USERNAME --password $SVN_PASSWORD"
	SVN_BASE=https://192.168.1.2/svn/repos
	TARGET_HOST=mbp-santa-rosa #TODO: prompt user for this, or let him pass it as cmdline argument

	#TODO: find something against svn's interactive ssl cert checking.  http://www.7php.net/svn-client-certificate-authentication-cache/ might help

	notify "**** From now on. everything will be automatic. Enjoy the show!"

        execute worker runtime_packages
}

worker_prepare_disks ()
{
	#TODO : use existing functions to do this + fix encryption and stuff
	true	
}

worker_package_list ()
{
	$SVN export $SVN_BASE/ddm-configs/$TARGET_HOST/trunk/package-list /home/arch/fifa/package-list || die_error "Could not export package list!"
}


worker_configure_home ()
{
	#checkout from svn
	true
}


worker_install_bootloader ()
{
	install-grub /dev/sda
}

