#!/bin/sh

# See http://wiki.archlinux.org/index.php/Yaourt

_runtime_yaourt ()
{
	if ! list_pacman_repos runtime | grep -q archlinuxfr
	then
		add_pacman_repo runtime archlinuxfr 'Server = http://repo.archlinux.fr/i686'
	fi
	$PACMAN -Sy yaourt || die_error "_runtime_yaourt Cannot install yaourt"
	YAOURT=`sed 's/pacman/yaourt/' <<< $PACMAN`
	YAOURT_TARGET=`sed 's/pacman/yaourt/' <<< $PACMAN_TARGET`
}


_yaourt_replace_pacman ()
{
	_runtime_yaourt
	PACMAN=$YAOURT
	PACMAN_TARGET=$YAOURT_TARGET
}

